url: https://rustworkshop.co
baseurl:

# Site settings
title: The Rust Workshop
email: hello@rustworkshop.co
description: "A Specialist Rust Development Shop"


# Team names, titles and social links
people:
- name: Tim Abell
  pic: tim
  position: Founder
  social:
    - title: twitter
      url: https://twitter.com/tim_abell
    - title: stack-overflow
      url: https://stackoverflow.com/users/10245/tim-abell
    - title: github
      url: https://github.com/timabell
- name: Luxagen
  pic: luxagen
  position: Rust Engineer
  social:
    - title: github
      url: https://github.com/luxagen
- name: You?
  position: Join our growing team
  pic: farhan-visuals-pVdnlXajLqQ-unsplash

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
#social:
#  - title: github
#    url: https://github.com/rustworkshop

# Postal address (add as many lines as necessary)
address:
  - line: Apollo House Hallam Way, Whitehills Business Park, Blackpool, FY4 5FS

# Build settings
markdown: kramdown
permalink: pretty
