url: https://rustworkshop.co
baseurl:

# Site settings
title: The Rust Workshop
email: hello@rustworkshop.co
description: "A Specialist Rust Development Shop"


# Team names, titles and social links
people:
- pic: tim
  name: Tim Abell
  position: Founder
  bio: 20+ years of professional coding & contracting | delivered many projects in many technologies | entrepreneur | mentor | communicator | endless nerd | loves to talk about technology and business
  social:
    - title: twitter
      url: https://twitter.com/tim_abell
    - title: stack-overflow
      url: https://stackoverflow.com/users/10245/tim-abell
    - title: github
      url: https://github.com/timabell
- pic: luxagen
  name: Luxagen
  position: Rust Engineer
  bio: 20+ years experience of delivering software | expert C++ programmer | musician | rust programmer
  social:
    - title: github
      url: https://github.com/luxagen
- pic: farhan-visuals-pVdnlXajLqQ-unsplash
  name: You?
  position: Join our growing team
  bio: We're always on the look out for great people to join our ambitious and growing software consultancy. Use the contact button to start the conversation.

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
#social:
#  - title: github
#    url: https://github.com/rustworkshop

# Postal address (add as many lines as necessary)
address:
  - line: Apollo House Hallam Way, Whitehills Business Park, Blackpool, FY4 5FS

# Build settings
markdown: kramdown
permalink: pretty
