url: https://rustworkshop.co
baseurl:

# Site settings
title: The Rust Workshop
email: tim@charmconsulting.co.uk
description: "A Specialist Rust Development Shop"


# Team names, titles and social links
people:
- name: Tim Abell
  pic: 1
  position: Founder
  social:
    - title: twitter
      url: tim_abell
    - title: facebook
      url: #
    - title: stack-overflow
      url: #


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: #
  - title: facebook
    url:
  - title: stack-overflow
    url: #
  - title: bitbucket 
    url: #
  - title: github
    url: https://github.com/rustworkshop

# Postal address (add as many lines as necessary)
address:
  - line: Apollo House Hallam Way, Whitehills Business Park, Blackpool, FY4 5FS

# Build settings
markdown: kramdown
permalink: pretty